import {
  DashboardStats,
  ResumeDocument,
  AnalyticsDataPoint,
  InterviewHistoryItem,
  AIFeedbackPoint,
  CareerMilestone,
  SkillGapItem,
} from "@/types/dashboard";

export const initialDashboardStats: DashboardStats = {
  atsScore: 88,
  atsScoreChange: 8,
  interviewsCompleted: 14,
  interviewsCompletedChange: 4,
  averageInterviewScore: 86,
  averageInterviewScoreChange: 12,
  careerGoalProgress: 78,
  careerGoalProgressChange: 9,
  targetRole: "Senior Full-Stack & Distributed Systems Engineer",
  readinessLevel: "Senior Ready",
};

export const sampleResumes: ResumeDocument[] = [
  {
    id: "res-01",
    title: "Senior_FullStack_Cloud_Architect_2025.pdf",
    targetRole: "Senior Full-Stack Engineer / Distributed Systems",
    lastUpdated: "Updated 2 hours ago",
    atsScore: 88,
    fileName: "Senior_FullStack_Cloud_Architect_2025.pdf",
    fileSize: "148 KB",
    matchedKeywords: [
      "Next.js 15",
      "TypeScript",
      "PostgreSQL",
      "Docker",
      "Redis Caching",
      "Microservices",
      "AWS ECS",
      "GraphQL",
      "CI/CD Pipelines",
      "Tailwind CSS",
    ],
    missingKeywords: [
      "Kubernetes (K8s)",
      "gRPC / Protobuf",
      "Distributed Tracing (OpenTelemetry)",
      "Terraform IaC",
    ],
    summary:
      "High-impact Senior Full-Stack Engineer with 5+ years architecting scalable cloud-native web applications, distributed backend services, and high-conversion React/Next.js frontends. Proven track record reducing API latency by 45% and leading cross-functional engineering pods.",
    experienceSnippet: [
      {
        role: "Senior Software Engineer",
        company: "TechScale Solutions",
        period: "2023 - Present",
        highlights: [
          "Architected real-time event streaming pipeline processing 12M+ daily events using Node.js, Redis Streams, and PostgreSQL, reducing latency by 42%.",
          "Spearheaded Next.js 15 SSR migration for flagship SaaS platform, elevating Core Web Vitals to 99/100 and driving a 28% increase in user retention.",
          "Mentored 6 junior/mid engineers and established standardized CI/CD pipelines with GitHub Actions and Docker.",
        ],
      },
      {
        role: "Full-Stack Developer",
        company: "Nexus Digital Agency",
        period: "2021 - 2023",
        highlights: [
          "Engineered 14+ responsive web applications with TypeScript, React, and REST APIs, serving 500k+ active monthly users.",
          "Implemented automated unit & end-to-end test suites (Jest, Playwright) achieving 87% code coverage and eliminating production regressions.",
        ],
      },
    ],
    skills: [
      "React / Next.js",
      "TypeScript",
      "Node.js & Express",
      "PostgreSQL & Prisma",
      "Redis",
      "Docker",
      "AWS (S3, ECS, Lambda)",
      "Tailwind CSS",
      "REST & GraphQL",
      "System Design",
    ],
    education: {
      degree: "B.S. in Computer Science & Engineering",
      school: "University of Technology",
      year: "2021",
    },
  },
  {
    id: "res-02",
    title: "AI_Prompt_Engineering_FullStack_Specialist.pdf",
    targetRole: "Full-Stack AI Application Engineer",
    lastUpdated: "Updated 3 days ago",
    atsScore: 82,
    fileName: "AI_Prompt_Engineering_FullStack_Specialist.pdf",
    fileSize: "132 KB",
    matchedKeywords: [
      "LLM Integration",
      "Google Gemini API",
      "Next.js",
      "TypeScript",
      "RAG Pipelines",
      "Vector DBs",
      "Python",
    ],
    missingKeywords: [
      "LangChain",
      "Fine-Tuning",
      "Model Quantization",
    ],
    summary:
      "Full-Stack AI Developer specializing in integrating Generative AI models (Gemini, Claude, GPT-4) into production enterprise web applications with sub-second streaming responses.",
    experienceSnippet: [
      {
        role: "AI Application Specialist",
        company: "Cognitive Labs",
        period: "2024 - Present",
        highlights: [
          "Built autonomous resume parsing agent utilizing Google Gemini 2.0 Flash, indexing 100k+ resumes with 96% accuracy.",
          "Designed streaming SSE endpoints for low-latency generative chat feedback.",
        ],
      },
    ],
    skills: ["Gemini API", "Next.js", "TypeScript", "Python", "Pinecone", "Tailwind CSS"],
    education: {
      degree: "B.S. in Software Engineering",
      school: "Polytechnic Institute",
      year: "2022",
    },
  },
];

export const initialAnalyticsData: AnalyticsDataPoint[] = [
  { date: "Feb 10", overall: 64, technical: 65, communication: 62, problemSolving: 60, sessionName: "Initial Assessment" },
  { date: "Feb 15", overall: 68, technical: 70, communication: 65, problemSolving: 66, sessionName: "React State Architecture" },
  { date: "Feb 20", overall: 73, technical: 74, communication: 70, problemSolving: 72, sessionName: "Behavioral: Conflict & Ownership" },
  { date: "Feb 26", overall: 76, technical: 79, communication: 73, problemSolving: 75, sessionName: "Postgres & Sharding Strategy" },
  { date: "Mar 02", overall: 81, technical: 84, communication: 78, problemSolving: 80, sessionName: "System Design: Rate Limiter" },
  { date: "Mar 05", overall: 83, technical: 85, communication: 81, problemSolving: 82, sessionName: "Next.js 15 Server Components" },
  { date: "Mar 08", overall: 86, technical: 89, communication: 84, problemSolving: 85, sessionName: "Distributed Microservices" },
  { date: "Mar 11", overall: 89, technical: 92, communication: 86, problemSolving: 88, sessionName: "Full-Stack Mock Final Simulation" },
];

export const sampleInterviewHistory: InterviewHistoryItem[] = [
  {
    id: "int-01",
    role: "Senior Full-Stack Engineer",
    difficulty: "senior",
    type: "system-design",
    score: 91,
    completedAt: "Today at 2:30 PM",
    durationMinutes: 28,
    questionCount: 5,
    keyStrength: "Comprehensive trade-off comparison between Cassandra and PostgreSQL for high-write feeds.",
    keyImprovement: "Include specific estimations for memory cache eviction policies (LRU sizing).",
    grade: "Senior Hire Ready",
  },
  {
    id: "int-02",
    role: "Staff Frontend Architect",
    difficulty: "lead",
    type: "technical",
    score: 87,
    completedAt: "Yesterday at 6:15 PM",
    durationMinutes: 24,
    questionCount: 4,
    keyStrength: "Deep mastery of React Server Components, Streaming SSR, and hydration bottlenecks.",
    keyImprovement: "Quantify bundle size impact with dynamic tree-shaking examples.",
    grade: "Senior Hire Ready",
  },
  {
    id: "int-03",
    role: "Engineering Lead / Manager",
    difficulty: "senior",
    type: "behavioral",
    score: 84,
    completedAt: "Mar 08, 2025",
    durationMinutes: 22,
    questionCount: 4,
    keyStrength: "Clear adherence to STAR framework with crisp Result quantification.",
    keyImprovement: "Compress the Situation background to reserve more airtime for leadership Actions.",
    grade: "Mid/Senior Hire",
  },
  {
    id: "int-04",
    role: "Distributed Cloud Backend Engineer",
    difficulty: "senior",
    type: "technical",
    score: 82,
    completedAt: "Mar 05, 2025",
    durationMinutes: 30,
    questionCount: 6,
    keyStrength: "Accurate implementation of idempotency keys in distributed payment workflows.",
    keyImprovement: "Discuss dead-letter queues and retry backoff strategies in more detail.",
    grade: "Mid/Senior Hire",
  },
  {
    id: "int-05",
    role: "Full-Stack Generalist",
    difficulty: "mid",
    type: "mixed",
    score: 79,
    completedAt: "Feb 28, 2025",
    durationMinutes: 20,
    questionCount: 4,
    keyStrength: "High enthusiasm and structured API design methodology.",
    keyImprovement: "Review SQL isolation levels (Read Committed vs Serializable).",
    grade: "Mid-Level Ready",
  },
];

export const sampleAIFeedbackPoints: AIFeedbackPoint[] = [
  {
    id: "fb-01",
    type: "strength",
    category: "Technical Depth",
    title: "Mastery of Modern React & Distributed Web Systems",
    description: "Your responses on SSR streaming, server actions, and database connection pooling scored in the 94th percentile across senior candidates.",
    actionableTip: "Highlight this in hiring manager screenings by discussing how you debugged SSR hydration bottlenecks.",
    impactBadge: "High Impact",
  },
  {
    id: "fb-02",
    type: "strength",
    category: "STAR Communication",
    title: "Quantified Impact in Behavioral Responses",
    description: "85% of your leadership answers successfully included measurable metrics (e.g. latency dropped 42%, 6 engineers mentored).",
    actionableTip: "Keep this formula consistent across all recruiter calls.",
    impactBadge: "High Impact",
  },
  {
    id: "fb-03",
    type: "improvement",
    category: "System Architecture",
    title: "Distributed Caching & Invalidation Nuances",
    description: "In system design rounds, caching is frequently proposed without specifying Cache-Aside vs Write-Through or TTL race condition handling.",
    actionableTip: "Practice naming Redis eviction strategies (LRU/LFU) and dogpiling prevention (mutex locks / probabalistic early expiration).",
    impactBadge: "Critical",
  },
  {
    id: "fb-04",
    type: "improvement",
    category: "Resume & Keywords",
    title: "Missing Tier-1 ATS Keywords in Resume",
    description: "Your primary resume is missing high-signal keywords: 'Kubernetes (K8s)', 'Distributed Tracing', and 'Terraform IaC'.",
    actionableTip: "Use one-click AI Optimization to embed these into your cloud deployment bullets.",
    impactBadge: "Quick Win",
  },
];

export const initialCareerMilestones: CareerMilestone[] = [
  {
    id: "ms-1",
    title: "ATS Resume Score > 85",
    description: "Optimize resume with quantified Google XYZ bullet formulas and verified keywords.",
    category: "Resume",
    completed: true,
    dueDate: "Completed",
    weight: 20,
  },
  {
    id: "ms-2",
    title: "Deploy Live Portfolio with 2 Production Full-Stack Projects",
    description: "Showcase Next.js 15, PostgreSQL database, authentication, and live cloud deployment.",
    category: "Portfolio",
    completed: true,
    dueDate: "Completed",
    weight: 20,
  },
  {
    id: "ms-3",
    title: "Complete 10+ AI Mock Interviews with Avg Score > 80%",
    description: "Simulate technical, behavioral, and system design interviews to build conversational fluidity.",
    category: "Interview",
    completed: true,
    dueDate: "Completed (14 Sessions)",
    weight: 20,
  },
  {
    id: "ms-4",
    title: "Master High-Frequency System Design Patterns",
    description: "Practice Rate Limiters, URL Shortener, Notification Engine, and Distributed Caching architectures.",
    category: "Coding",
    completed: true,
    dueDate: "Completed",
    weight: 15,
  },
  {
    id: "ms-5",
    title: "Solve 50+ LeetCode Medium/Hard Core Patterns",
    description: "Master Two Pointers, Sliding Window, Dynamic Programming, and Graph Traversals.",
    category: "Coding",
    completed: false,
    dueDate: "In Progress (38/50 Completed)",
    weight: 15,
  },
  {
    id: "ms-6",
    title: "Outreach & Referral Pipeline for 20 Tier-1 Tech Companies",
    description: "Connect with engineering managers, tech leads, and alumni on LinkedIn with tailored pitches.",
    category: "Networking",
    completed: false,
    dueDate: "Target: Within 2 Weeks",
    weight: 10,
  },
];

export const sampleSkillGaps: SkillGapItem[] = [
  {
    name: "Kubernetes (K8s) Cluster Ops",
    category: "DevOps & Cloud",
    marketDemandScore: 94,
    status: "Identified Gap",
    recommendedCourseOrProject: "Deploy microservices on Minikube with Helm charts & Ingress.",
  },
  {
    name: "Distributed Tracing (OpenTelemetry)",
    category: "Distributed Systems",
    marketDemandScore: 89,
    status: "In Progress",
    recommendedCourseOrProject: "Instrument Next.js and Node.js backend with Jaeger/Prometheus.",
  },
  {
    name: "Redis Distributed Caching & Redlock",
    category: "Core Backend",
    marketDemandScore: 92,
    status: "Acquired",
    recommendedCourseOrProject: "Mastered in Recent Mock Interview (91% Score).",
  },
  {
    name: "Terraform Infrastructure as Code",
    category: "DevOps & Cloud",
    marketDemandScore: 86,
    status: "Identified Gap",
    recommendedCourseOrProject: "Provision AWS VPC, ECS cluster, and RDS PostgreSQL via HCL.",
  },
];
